debug

diff --git a/.github/workflows/build_and_push.yaml b/.github/workflows/build_and_push.yaml
--- a/.github/workflows/build_and_push.yaml
+++ b/.github/workflows/build_and_push.yaml
@@ -22,8 +22,9 @@ jobs:
 
       - name: Check if ENV_FILE is set
         run: |
-          if [ -z "${{ ENV_FILE }}" ]; then
-            echo "ENV_FILE is not set"
+          if [ -z "${{ secrets.ENV_FILE }}" ]; then
+            echo "::error::ENV_FILE is not set"
+            exit 1
           else
             echo "ENV_FILE is set"
           fi
