add python version with variable

diff --git a/.github/workflows/pytest.yaml b/.github/workflows/pytest.yaml
--- a/.github/workflows/pytest.yaml
+++ b/.github/workflows/pytest.yaml
@@ -12,13 +12,25 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: Check out the code
-        uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.ENV_FILE }}" ]; then
+            echo "Error: Secret ENV_FILE is not set!"
+            exit 1
+          fi
+
+      - name: Create .env file from secret
+        run: |
+          echo "${{ secrets.ENV_FILE }}" > .env
+        shell: bash
 
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.12'
+          python-version: '${{ env.PYTHON_VERSION }}'
 
       - name: Install Poetry
         run: |
@@ -29,11 +41,6 @@ jobs:
         run: |
           poetry lock
           poetry install
-
-      - name: Create .env file from secret
-        run: |
-          echo "${{ secrets.ENV_FILE }}" > .env
-        shell: bash
 
       - name: Install Docker Compose
         run: |
diff --git a/.github/workflows/ruff.yml b/.github/workflows/ruff.yml
--- a/.github/workflows/ruff.yml
+++ b/.github/workflows/ruff.yml
@@ -6,14 +6,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: Check required secrets
+      run: |
+        if [ -z "${{ secrets.ENV_FILE }}" ]; then
+          echo "Error: Secret ENV_FILE is not set!"
+          exit 1
+        fi
+
+    - name: Create .env file from secret
+      run: |
+        echo "${{ secrets.ENV_FILE }}" > .env
+      shell: bash
+
     - name: Set up Python
-      uses: actions/setup-python@v5
+      uses: actions/setup-python@v4
       with:
-        python-version: 3.12
+        python-version: '${{ env.PYTHON_VERSION }}'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ruff
+
     - name: Run Ruff
       run: ruff check --output-format=github .
