Bugfix/refactor compose and workflow files (#293)
Тикет вашего PR (если есть):
    ___288___

- Постарался сделать единообразие в compose-файлах и workflow.
- Добавил в конфигурации динамические переменные вместо жестко заданных.
- Поправил файл с переменными окружения. Теперь из .env.example можно
сделать .env без изменений и сразу использовать в разработке.


Когда создаёте PR, убедитесь, что:

- [ ] синхронизировали изменения кода с [ER-диаграммой базы
данных](https://app.erdlab.io/designer/schema/1736745715-tabit) связей
моделей
- [ ] убедились, что модель OpenAPI проверена (в Swagger отображаются
изменения)
- [ ] тесты все пройдены и нет конфликтов
- [ ] созданы необходимые миграции

Когда ваш PR смержен:

- [ ] если у вас были изменения в API, сообщите об этом команде Фронта,
им это важно знать!

---------

Co-authored-by: Andrey Zherdetskiy <aszherdetskiy@gmail.com>

diff --git a/.github/workflows/ruff.yml b/.github/workflows/ruff.yml
--- a/.github/workflows/ruff.yml
+++ b/.github/workflows/ruff.yml
@@ -6,14 +6,35 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: Check required secrets
+      run: |
+        if [ -z "${{ secrets.ENV_FILE }}" ]; then
+          echo "::error::Secret ENV_FILE is not set!"
+          exit 1
+        fi
+
+    - name: Extract Python version
+      id: extract_py_ver
+      run: |
+        VERSION=$(echo "${{ secrets.ENV_FILE }}" | grep '^PYTHON_VERSION=' | cut -d'=' -f2)
+        if [ -z "$VERSION" ]; then
+          echo "::error::PYTHON_VERSION not found in ENV_FILE from secrets!"
+          exit 1
+        fi
+        echo "PYTHON_VERSION=$VERSION" >> $GITHUB_ENV
+
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
-        python-version: 3.12
+        python-version: '${{ env.PYTHON_VERSION }}'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ruff
+
     - name: Run Ruff
       run: ruff check --output-format=github .
