тестовый деплой в VPS

diff --git a/.github/workflows/stage_deploy.yaml b/.github/workflows/stage_deploy.yaml
--- a/.github/workflows/stage_deploy.yaml
+++ b/.github/workflows/stage_deploy.yaml
@@ -9,8 +9,8 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    environment:
-      name: dev_deploy
+    # environment:
+    #   name: dev_deploy
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -22,12 +22,9 @@ jobs:
           context: .
           file: infra/stage/stage.Dockerfile
           push: true
-          tags: ${{ github.sha }}
-      
-      - name: Delete unnecessary files
-        run: |
-          rm -r infra/stage
-          rm -r infra/dev
+          tags: |
+            ghcr.io/${{ github.repository }}:latest
+            ghcr.io/${{ github.repository }}:${{ github.sha }}
 
       - name: Stopping old containers
         uses: appleboy/ssh-action@master
@@ -36,15 +33,19 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            STATUS="$(systemctl is-active tabit.service)"
-            if [ "${STATUS}" = "active" ]; then
-              sudo systemctl stop tabit.service
-              echo "Stopping old containers"
+            if systemctl list-units --full -all | grep -q "tabit.service"; then
+              STATUS="$(systemctl is-active tabit.service)"
+              if [ "${STATUS}" = "active" ]; then
+                sudo systemctl stop tabit.service
+                echo "Stopping old containers"
+              else
+                echo "No active containers"
+              fi
             else
-              echo "No active containers"
+              echo "Service tabit.service does not exist, skipping stop"
             fi
 
-      - name: Copy infra via ssh
+      - name: Copy infra via SSH
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.HOST }}
@@ -55,7 +56,7 @@ jobs:
           rm: true
           strip_components: 1
 
-      - name: Execute commands on VPS
+      - name: Configure environment variables on VPS
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
@@ -64,10 +65,27 @@ jobs:
           script: |
             cd ${{ env.DEPLOY_PATH }}
             touch .env
-
+            if [[ -z "${{ secrets.ENV_FILE }}" ]]; then
+              echo "Error: ENV_FILE is not set!"
+              exit 1
+            fi
             echo "${{ secrets.ENV_FILE }}" > .env
 
-            cd infra/stage/
-            docker system prune --force
+      - name: Restart services
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd ${{ env.DEPLOY_PATH }}/infra/stage/
+            sudo systemctl daemon-reload
+            sudo systemctl restart tabit.service
+            docker-compose -f infra/stage/docker-compose.stage.yaml down
+            docker-compose -f infra/stage/docker-compose.stage.yaml pull
+            docker-compose -f infra/stage/docker-compose.stage.yaml up -d --force-recreate
 
-            sudo cp -f /home/dev_deploy/app/infra/stage/tabit.service /etc/systemd/system/tabit.service
+      - name: Delete unnecessary files (after deploy)
+        run: |
+          rm -r infra/stage
+          rm -r infra/dev
