add more variables to workflow

diff --git a/.github/workflows/stage_deploy.yaml b/.github/workflows/stage_deploy.yaml
--- a/.github/workflows/stage_deploy.yaml
+++ b/.github/workflows/stage_deploy.yaml
@@ -6,9 +6,6 @@ on:
       - dev
   workflow_dispatch:
 
-env:
-  IMAGE_NAME: studio-yandex-practicum/tabit
-
 jobs:
   build:
     uses: ./.github/workflows/build_and_push.yaml
@@ -46,6 +43,22 @@ jobs:
             echo "Error: Secret ENV_FILE is not set!"
             exit 1
           fi
+
+      - name: Extract Registry and Image name
+        run: |
+          REGISTRY=$(echo "${{ secrets.ENV_FILE }}" | grep '^CONTAINER_REGISTRY=' | cut -d'=' -f2)
+          if [ -z "$REGISTRY" ]; then
+            echo "::error::CONTAINER_REGISTRY not found in ENV_FILE from secrets!"
+            exit 1
+          fi
+          echo "CONTAINER_REGISTRY=$REGISTRY" >> $GITHUB_ENV
+
+          IMAGE=$(echo "${{ secrets.ENV_FILE }}" | grep '^IMAGE_NAME=' | cut -d'=' -f2)
+          if [ -z "$IMAGE" ]; then
+            echo "::error::IMAGE_NAME not found in ENV_FILE from secrets!"
+            exit 1
+          fi
+          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
