debug

diff --git a/.github/workflows/stage_deploy.yaml b/.github/workflows/stage_deploy.yaml
--- a/.github/workflows/stage_deploy.yaml
+++ b/.github/workflows/stage_deploy.yaml
@@ -11,8 +11,6 @@ jobs:
     uses: ./.github/workflows/build_and_push.yaml
     secrets:
       GHCR_PAT: ${{ secrets.GHCR_PAT }}
-      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-      USERNAME: ${{ secrets.USERNAME }}
       ENV_FILE: ${{ secrets.ENV_FILE }}
 
   deploy:
@@ -22,21 +20,21 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Check required secrets
+      - name: Check secrets
+        env:
+          HOST: ${{ secrets.HOST }}
+          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
+          GHCR_PAT: ${{ secrets.GHCR_PAT }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          ENV_FILE: ${{ secrets.ENV_FILE }}
         run: |
-          REQUIRED_SECRETS=("HOST" "USERNAME" "SSH_PRIVATE_KEY" "GHCR_PAT" "ENV_FILE")
-          MISSING_SECRETS=()
-
+          REQUIRED_SECRETS=("HOST" "SERVER_USERNAME" "GHCR_PAT" "SSH_PRIVATE_KEY" "ENV_FILE")
           for secret in "${REQUIRED_SECRETS[@]}"; do
             if [ -z "${!secret}" ]; then
-              MISSING_SECRETS+=("$secret")
+              echo "::error::Missing $secret"
+              exit 1
             fi
           done
-
-          if [ ${#MISSING_SECRETS[@]} -ne 0 ]; then
-            echo "::error::Missing secrets: ${MISSING_SECRETS[*]}"
-            exit 1
-          fi
 
       - name: Create .env file from secret
         run: |
@@ -60,7 +58,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             if systemctl list-units --full -all | grep -q "tabit.service"; then
@@ -72,7 +70,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             find /home/${{ secrets.SERVER_USERNAME }}/tabit -mindepth 1 -maxdepth 1 ! -name ".ssh" -exec rm -rf {} +
@@ -82,7 +80,7 @@ jobs:
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: "infra/"
           target: "/home/${{ secrets.SERVER_USERNAME }}/tabit/"
@@ -92,7 +90,7 @@ jobs:
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: "pgadmin/"
           target: "/home/${{ secrets.SERVER_USERNAME }}/tabit/"
@@ -102,7 +100,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             sudo cp /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/tabit.service /etc/systemd/system/tabit.service
@@ -113,7 +111,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/
@@ -123,7 +121,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
@@ -139,7 +137,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             docker load -i /home/${{ secrets.SERVER_USERNAME }}/tabit/tmp/tabit.tar
@@ -149,7 +147,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd /home/${{ secrets.SERVER_USERNAME }}/tabit/infra/stage/
@@ -160,7 +158,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             docker exec ${{ env.APP_CONTAINER_NAME }} poetry run alembic upgrade head
@@ -169,7 +167,7 @@ jobs:
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             # Получаем список всех образов для проекта, сортируем по дате и удаляем все, кроме последних 5
